@startuml

skinparam classAttributeIconSize 0

class Instructor {
    +id : Integer
    +name : String
    +imageProfile : String
    +rating : Float
    +totalLessons : Integer
    +experience : Integer
    +location : String
    +pricePerHour : Decimal
    +bio : String
    +carModel : String
}

class Student {
    +id : Integer
    +name : String
    +email : String
    +phone : Integer
    +cpf : Integer
    +documentId : Integer
    +birthDate : Date
    +location : String
    +createdAt : DateTime
}

class Specialty {
    +id : Integer
    +name : String
}

class Category {
    +id : Integer
    +name : String
}

class Lesson {
    +id : Integer
    +lessonDate : Date
    +startTime : Time
    +endTime : Time
    +price : Decimal
    +status : String
    +lessonLocation : String
    +notes : String
    +createdAt : DateTime
}

class Payment {
    +id : Integer
    +amount : Decimal
    +method : String
    +status : String
    +paidAt : DateTime
}

class Review {
    +id : Integer
    +ratingScore : Integer
    +comment : String
    +createdAt : DateTime
}

class InstructorAvailability {
    +id : Integer
    +daysWeek : String
    +workingTime : String
    +lunchtime : String
    +blockedDays : String
}

' =====================
' RELACIONAMENTOS
' =====================

Instructor "1" -- "0..*" Lesson
Student "1" -- "0..*" Lesson

Lesson "1" -- "0..1" Payment

Lesson "1" -- "0..1" Review

Instructor "1" -- "0..*" Review
Student "1" -- "0..*" Review

Instructor "*" -- "*" Specialty
Student "*" -- "*" Specialty

Instructor "*" -- "*" Category
Student "*" -- "*" Category

Instructor "1" -- "1" InstructorAvailability

@enduml